from typing import Protocol, TypeVar, Optional, Any, List

T = TypeVar('T')


class IDatabaseSession(Protocol):
    def query(self, model: Any): ...
    def add(self, instance: Any): ...
    def delete(self, instance: Any): ...   # добавлен
    def commit(self): ...
    def rollback(self): ...
    def close(self): ...