from typing import Protocol, List, Optional, Any, Tuple
from PyQt5.QtCore import pyqtSignal
from utils.validation_errors import ValidationResult


class ICaptchaWidget(Protocol):
    solved: pyqtSignal
    def reset(self) -> None: ...
    def is_solved(self) -> bool: ...


class IAuthController(Protocol):
    def validate_credentials(self, login: str, password: str) -> ValidationResult: ...
    def authenticate(self, login: str, password: str) -> Optional[Any]: ...
    def is_user_blocked(self, login: str) -> bool: ...
    def get_attempts_info(self, login: str) -> Tuple[int, int]: ...
    def increment_attempts(self, login: str) -> None: ...


class IUserController(Protocol):
    def get_all_users(self) -> List[Any]: ...
    def get_roles(self) -> List[Any]: ...
    def validate_user_data(self, login: str, password: str = None,
                           last_name: str = "", first_name: str = "",
                           patronymic: str = "", phone: str = "",
                           is_edit: bool = False) -> ValidationResult: ...
    def add_user(self, login: str, password: str, role_name: str,
                 last_name: str = "", first_name: str = "", patronymic: str = "",
                 phone_number: str = "") -> bool: ...
    def update_user(self, user_id: int, login: str = None, password: str = None,
                    role_name: str = None, last_name: str = None,
                    first_name: str = None, patronymic: str = None,
                    phone_number: str = None) -> bool: ...
    def delete_user(self, user_id: int) -> bool: ...
    def unlock_user(self, user_id: int) -> bool: ...
    def is_phone_exists(self, phone: str, exclude_user_id: int = None) -> bool: ...