from typing import Protocol, List, Optional, Tuple
from PyQt5.QtCore import pyqtSignal
from sqlalchemy.orm import Session
from utils.validation_errors import ValidationResult
from models.user import User
from models.role import Role

class ISessionFactory(Protocol):
    def __call__(self) -> Session: ...


class ICaptchaWidget(Protocol):
    solved: pyqtSignal
    def reset(self) -> None: ...
    def is_solved(self) -> bool: ...


class ICaptchaService(Protocol):
    def shuffle(self) -> List[int]: ...
    def is_solved(self, current_order: List[int]) -> bool: ...
    def swap(self, order: List[int], i: int, j: int) -> List[int]: ...


class IUserRepository(Protocol):
    def get_all(self) -> List[User]: ...
    def get_by_id(self, user_id: int) -> Optional[User]: ...
    def get_by_login(self, login: str) -> Optional[User]: ...
    def add(self, user: User) -> User: ...
    def update(self, user: User) -> User: ...
    def delete(self, user_id: int) -> bool: ...
    def unlock(self, user_id: int) -> Optional[User]: ...
    def is_phone_exists(self, phone: str, exclude_user_id: Optional[int] = None) -> bool: ...


class IRoleRepository(Protocol):
    def get_all(self) -> List[Role]: ...
    def get_by_id(self, role_id: int) -> Optional[Role]: ...
    def get_by_name(self, name: str) -> Optional[Role]: ...


class IAuthService(Protocol):
    def authenticate(self, login: str, password: str) -> Optional[User]: ...
    def get_user_role_name(self, user: User) -> Optional[str]: ...
    def is_user_blocked(self, login: str) -> bool: ...
    def increment_attempts(self, login: str) -> None: ...
    def get_attempts_info(self, login: str) -> Tuple[int, int]: ...
    def user_exists(self, login: str) -> bool: ...
    def handle_login_attempt(self, login: str, password: str, captcha_solved: bool): ...


class INavigationManager(Protocol):
    def show_login(self) -> None: ...
    def on_authentication_success(self, user, role_name: str) -> None: ...


class IUserReader(Protocol):
    def get_all_users(self) -> List[User]: ...
    def get_user_by_id(self, user_id: int) -> Optional[User]: ...
    def get_user_by_login(self, login: str) -> Optional[User]: ...
    def get_roles(self) -> List[Role]: ...


class IUserWriter(Protocol):
    def add_user(self, data: dict) -> Optional[User]: ...
    def edit_user(self, user_id: int, data: dict) -> Optional[User]: ...
    def delete_user(self, user_id: int) -> bool: ...
    def unlock_user(self, user_id: int) -> bool: ...
    def update_user(self, user: User) -> Optional[User]: ...


class IUserValidator(Protocol):
    def validate_user_data(self, login: str, password: Optional[str] = None,
                           last_name: str = "", first_name: str = "",
                           patronymic: str = "", phone: str = "",
                           is_edit: bool = False) -> ValidationResult: ...
    def prepare_user_data(self, data: dict, is_edit: bool) -> Tuple[Optional[dict], str]: ...
    def is_phone_exists(self, phone: str, exclude_user_id: Optional[int] = None) -> bool: ...


class IUserService(IUserReader, IUserWriter, IUserValidator):
    pass